[global.config]
  as = 65000
  router-id = "192.0.2.1"

[[bmp-servers]]
[bmp-servers.config]
  address = "127.0.0.1"
  port = 5001
  route-monitoring-policy = "all"

[[neighbors]]
[neighbors.config]
  neighbor-address = "192.0.2.99"
  peer-as = 65001
