foreground = yes
debug = 7
output = /dev/stdout

[BMPS]
client = yes
accept = 0.0.0.0:5001
connect = 10.1.1.101:7001
cert = /etc/stunnel/server.crt
key  = /etc/stunnel/server.key
CAfile = /etc/stunnel/ca.crt
verify = 2
requireCert = yes
options = NO_TLSv1
options = NO_TLSv1_1
options = NO_TLSv1_2
sslVersion = TLSv1.3
ciphersuites = TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256
